In [2]:
import numpy as np

In [3]:
"""
NumPy Array Attributes
"""

print(np.arange(3))
print(np.arange(3,9))
print(np.arange(3,9,3))

[0 1 2]
[3 4 5 6 7 8]
[3 6]


In [4]:
# Random number generator

np.random.seed(0)
arr1 = np.random.randint(100, size=(3, 4, 5))
print(arr1)

[[[44 47 64 67 67]
  [ 9 83 21 36 87]
  [70 88 88 12 58]
  [65 39 87 46 88]]

 [[81 37 25 77 72]
  [ 9 20 80 69 79]
  [47 64 82 99 88]
  [49 29 19 19 14]]

 [[39 32 65  9 57]
  [32 31 74 23 35]
  [75 55 28 34  0]
  [ 0 36 53  5 38]]]


In [5]:
# Attributes

np.random.seed(1)
arr = np.random.randint(10, size=(3, 4))
print(arr)

print("arr.ndim = ", arr.ndim)
print("arr.shape = ", arr.shape)
print("arr.size = ", arr.size)
print("arr.dtype = ", arr.dtype)
print("arr.itemsize = ", arr.itemsize)
print("arr.nbytes = ", arr.nbytes)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
arr.ndim =  2
arr.shape =  (3, 4)
arr.size =  12
arr.dtype =  int32
arr.itemsize =  4
arr.nbytes =  48


In [6]:
"""
slicing
"""

arr = np.random.randint(10, size=(3, 4))
print(arr)
print(arr[:2, :3])

[[5 2 4 2]
 [4 7 7 9]
 [1 7 0 6]]
[[5 2 4]
 [4 7 7]]


In [7]:
# Multi-dimensional Subarrays

np.random.seed(2)
arr = np.random.randint(10, size=(6,8))
print(arr)

arr_sum= arr[:2,:2]
print(arr_sum)

arr_sum[0, 0]=99
print(arr_sum)

print(arr)

[[8 8 6 2 8 7 2 1]
 [5 4 4 5 7 3 6 4]
 [3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4]
 [1 7 8 2 9 8 7 1]
 [6 8 5 9 9 9 3 0]]
[[8 8]
 [5 4]]
[[99  8]
 [ 5  4]]
[[99  8  6  2  8  7  2  1]
 [ 5  4  4  5  7  3  6  4]
 [ 3  7  6  1  3  5  8  4]
 [ 6  3  9  2  0  4  2  4]
 [ 1  7  8  2  9  8  7  1]
 [ 6  8  5  9  9  9  3  0]]


In [8]:
"""
Subarrays as no-copy views
"""

np.random.seed(3)
arr = np.random.randint(10, size=[6, 8])
print(arr)

arr_sub = arr[:2, :2].copy()
print(arr_sub)

arr_sub[0,0] = 99
print(arr_sub)

print(arr)


[[8 9 3 8 8 0 5 3]
 [9 9 5 7 6 0 4 7]
 [8 1 6 2 2 1 3 5]
 [8 1 8 7 8 1 0 5]
 [4 1 5 4 7 6 0 0]
 [9 2 4 5 8 8 7 5]]
[[8 9]
 [9 9]]
[[99  9]
 [ 9  9]]
[[8 9 3 8 8 0 5 3]
 [9 9 5 7 6 0 4 7]
 [8 1 6 2 2 1 3 5]
 [8 1 8 7 8 1 0 5]
 [4 1 5 4 7 6 0 0]
 [9 2 4 5 8 8 7 5]]


In [4]:
"""
Reshaping of Arrays
"""

arr = np.arange(1,10)
print(arr)
grid = arr.reshape(3,3)
print(grid)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#np.newaxis

arr = np.array([3,5,8])
print(arr)
print(arr.shape, "\n")

arr_new = arr[np.newaxis, :]
print(arr_new)
print(arr_new.shape, '\n')

arr_new = arr[:, np.newaxis]
print(arr_new)
print(arr_new.shape, '\n')

[3 5 8]
(3,) 

[[3 5 8]]
(1, 3) 

[[3]
 [5]
 [8]]
(3, 1) 



In [25]:
"""
Array Concatenation
"""

arr_1 = np.array([[1, 2, 3],[1, 2, 3]])
arr_2 = np.array([[4, 5, 6],[4, 5, 6]])
arr_3 = np.array([[7, 8, 9],[7, 8, 9]])

arr_total = np.concatenate([arr_1, arr_2, arr_3], axis=0)
print(arr_total)

arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)

arr_total = np.hstack([arr_1, arr_2, arr_3])
print(arr_total)

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [34]:
"""
Array splitting
"""

arr = [1, 2, 3, 4, 5, 6, 7, 8]
print(arr, '\n')

arr_1, arr_2, arr_3 = np.split(arr, [3, 8])
print(arr_1, arr_2)

[1, 2, 3, 4, 5, 6, 7, 8] 

[1 2 3] [4 5 6 7 8]
